### ISSUE TITLE
Can't access extension methods

### ISSUE THREAD

**Issue by delizondo** [a14n/dart-google-maps#101]
Hi 

First of all, thanks for this library, I've been using it for a while with Flutter Web, and it's great. However, today I've updated the library to the latest version, and I'm getting error accessing some extension methods.

The above code worked fine in previous versions of this library, but only when update it, it's causing me the errors showed in the screenshot.

Not sure how to access this methods, any suggestion?

<img width="566" alt="Screen Shot 2021-04-06 at 08 26 00" src="https://user-images.githubusercontent.com/1301103/113726832-cbf2d900-96b1-11eb-98f1-c5cb33339c1b.png">

**Comment by a14n** [comment]
Strange! Extensions are defined in the same library and should be valid as any other method. Did you try to restart your IDE? What's the current dart version in your pubspec.yaml ?

**Comment by delizondo** [comment]
Using VSCode as my main IDE, and no, restarting the IDE.

```
delizondo@MacBook-Pro fixar_admin % flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.4, on Mac OS X 10.15.7 19H524 darwin-x64, locale en)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[!] Xcode - develop for iOS and macOS
    ✗ CocoaPods installed but not working.
        You appear to have CocoaPods installed but it is not working.
        This can happen if the version of Ruby that CocoaPods was installed with is different from the one being used to invoke it.
        This can usually be fixed by re-installing CocoaPods.
      To re-install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.55.0)
[✓] Connected device (1 available)
```


My Dart version in my pubspec.yaml is

`environment:
  sdk: ">=2.3.0 <3.0.0"`

**Comment by a14n** [comment]
What's the version of `google_maps` package?

**Comment by delizondo** [comment]
> What's the version of `google_maps` package?

```google_maps: ^5.1.0```

**Comment by a14n** [comment]
Strange that pub accept that as `google_maps: ^5.1.0` requires that your lower bound in the sdk constraint should be 2.12.0.

After bumping your sdk constraint to `environment: sdk: ">=2.12.0 <3.0.0"` it should be ok.

**Comment by delizondo** [comment]
@a14n thanks! I'll take a look at that. I've upgraded the sdk constraint to ```>=2.12.0 <3.0.0``` and it's complaining everywhere about null safety, but that's another issue. I'll get back to you if the error persist after checking the null safety issue.

**Comment by delizondo** [comment]
@a14n something I've found is that even if I downgrade the google_maps library to version 4.0.0 (prior to null safety changes) I get the same error as stated above. 

In the release notes, for version 4.0.0 the change was:
- Migrate from dart:js to package:js.

**Comment by a14n** [comment]
Extensions are enabled starting from sdk 2.6.0. I guess that's the reason fo your failures.

**Comment by delizondo** [comment]
Updated the sdk to 
```sdk: '>=2.10.0 <3.0.0' ```

And the google_maps library to 
```google_maps: ^4.0.0```

Restarted the IDE, did a pub get packages, and the error persist, same as the original error in the screenshot

**Comment by a14n** [comment]
I'm sorry but I don't have other ideas without code access :-/ Is your project public?

**Comment by delizondo** [comment]
> I'm sorry but I don't have other ideas without code access :-/ Is your project public?

No, it's a private repo, but I'll try to create a public example project to show this issue

**Comment by delizondo** [comment]
@a14n I've created a new example project with and was able to reproduce the issue.

The repo is: [https://github.com/delizondo/Flutter_Maps_example](https://github.com/delizondo/Flutter_Maps_example)

The error should be visible [here](https://github.com/delizondo/Flutter_Maps_example/blob/master/flutter_map_example/lib/map_parent_widget.dart#L26)

**Comment by a14n** [comment]
Thanks for the reproduction. Too make it work you only have to add an import:

```diff
diff --git a/flutter_map_example/lib/map_parent_widget.dart b/flutter_map_example/lib/map_parent_widget.dart
index 90b7916..d83a562 100644
--- a/flutter_map_example/lib/map_parent_widget.dart
+++ b/flutter_map_example/lib/map_parent_widget.dart
@@ -1,4 +1,5 @@
 import 'package:flutter/material.dart';
+import 'package:google_maps/google_maps.dart';
 import 'package:google_maps/google_maps_places.dart';
 
 import 'map_location_notifier.dart';
```

**Comment by delizondo** [comment]
That's it!! Thanks a lot! it worked! The only question I have now is why the import is not suggested in both VSCode and Android Studio

**Comment by a14n** [comment]
>The only question I have now is why the import is not suggested in both VSCode and Android Studio

That's another problem for another repo ;)
