### ISSUE TITLE
Google Maps drawing manager

### ISSUE THREAD

**Issue by ozz-rjq** [a14n/dart-google-maps#102]
Is it possible to add drawing manager tool to this library (and Flutter)?
https://developers.google.com/maps/documentation/javascript/drawinglayer

**Comment by a14n** [comment]
It's already available for the web. See https://github.com/a14n/dart-google-maps/tree/master/example/09-libraries/drawing-tools

For Flutter you have to ask on https://github.com/flutter/flutter/issues
