### ISSUE TITLE
Move Camera not working

### ISSUE THREAD

**Issue by exilonX** [a14n/dart-google-maps#109]
My initial goal was to create a marker on the map and move the camera to that marker. 
I didn't find a way to animate the camera to the marker or something similar, but I found `GMap.moveCamera`

Tried it like below, but nothing happens, no idea how to actually debug it... 
```
    final mapOptions = MapOptions()
      ..zoom = 11
      ..center = state.mapState.mapCenter ??
          LatLng(44.431976571842604, 26.09025195973818)
      ..mapTypeControl = false
      ..fullscreenControl = false
      ..streetViewControl = false;

    map = GMap(elem, mapOptions);

    final CameraOptions cameraOptions = CameraOptions()
      ..center = position
      ..zoom = 12;

    map.moveCamera(cameraOptions);
```

Is moveCamera supported?

**Comment by a14n** [comment]
This feature looks only supported in beta channel for now. Do you use the [beta channel](https://developers.google.com/maps/documentation/javascript/versions?hl=en#choosing-the-beta-channel)?

**Comment by exilonX** [comment]
No, I'm not using the beta channel! 

To switch I just have to add the beta in the script tag?

**Comment by a14n** [comment]
Feel free to close the issue if that works for you.

**Comment by a14n** [comment]
To remove a marker juste set its `map` property to `null`

**Comment by exilonX** [comment]
Great! I didn't think that `marker.set` would actually do something! 
I could change the position         `originMarker?.set('position', position);`
