### ISSUE TITLE
Remove Polyline from Map

### ISSUE THREAD

**Issue by exilonX** [a14n/dart-google-maps#110]
I'm drawing a PolyLine like this: 
```
      var line = Polyline(PolylineOptions()
        ..path = multiLine
        ..strokeColor = colorHex
        ..strokeOpacity = 0.8
        ..strokeWeight = 5
        ..map = map);
```

But unfortunately I couldn't remove it from the map... 
I tried setting the Polyline's map property to null but it doesn't work...

**Comment by a14n** [comment]
The [polyline-remove example](https://github.com/a14n/dart-google-maps/tree/d766f26efd721da1fe95c5495eb87cd579ba88fc/example/05-drawing_on_map/polyline-remove) does exactly that and I can't see any issue running it.

Are you using `line.map = null` ?
