### ISSUE TITLE
Map view has Infinite Width

### ISSUE THREAD

**Issue by M4RZB4Ni** [a14n/dart-google-maps#111]
I used this library for show map and before update flutter to version 3 with SizedBox I could handle size of map plugin.
after update my flutter to version 3 , map have infinite width from right side of screen and SizedBox not effected on it.

**Comment by a14n** [comment]
This repository is specific to the google maps package for web. Your issue seems related to flutter and [google_maps_flutter](https://pub.dev/packages/google_maps_flutter). Please consider moving this issue to https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+maps%22
