### ISSUE TITLE
Fit bounds doesn't fit properly

### ISSUE THREAD

**Issue by exilonX** [a14n/dart-google-maps#112]
As far as I can imagine, `map.fitBounds(LatLngBounds)` should position the camera (change zoom level) to match the given bounds.

I noticed some problems with this feature:
1. I used the position of two markers as bounds. If I initialize LatLngBounds to ((47.072481, 15.417507), (48.185184, 16.376413)) it works fine and it fits correctly, but if I switch the two coordinates ( (48.185184, 16.376413), (47.072481, 15.417507)) then the bounds are set across the globe: 

![image](https://user-images.githubusercontent.com/961270/171342112-53e8ae2c-5eda-4618-9cab-a56d30c24eff.png)

2.  After using map.fitBounds zoom becomes unusable, apparently it changes (you can see some flashes on the map, text changing size) but it actually stays the same... 

Any ideas how to get around these issues ?

**Comment by exilonX** [comment]
Thanks for the fast reply, this fixes the Bounds across the globe problem. 

What about the zoom  ? As I told you it stops working, I can move the camera, but zoom in / zoom out doesn't change anything...

**Comment by a14n** [comment]
Testing on [example/02-events/event-closure](https://github.com/a14n/dart-google-maps/blob/d766f26efd721da1fe95c5495eb87cd579ba88fc/example/02-events/event-closure/page.dart#L18) I don't face the problem you describes. Perhaps something in your code is the cause of this zoom problem.

**Comment by exilonX** [comment]
Could be 👍 I will investigate further :) Hope to find out the problem...
