### ISSUE TITLE
Drawing a layer over part of the map 

### ISSUE THREAD

**Issue by exilonX** [a14n/dart-google-maps#115]
Hey! 

I've been working on a project that needs to somehow highlight that parts not all parts of the map are available to interact with. 
So I need a layer over the parts that are not included and keeping a normal, interractive map on the parts (countries) that are in the project. 

Something like this:
![image](https://user-images.githubusercontent.com/961270/181546766-5569f603-44c2-4096-a75b-1428326b4427.png)

The greyed out countries are excluded from the project and you can't interract with the map there, but in Romania for example it should be possible. 
Is it possible to build this layer ? I tried using KmlLayer but I'm not sure if it's what I need... 

```
final kmlLayer = KmlLayer(KmlLayerOptions()
        ..url =
            'http://googlemaps.github.io/kml-samples/kml/Placemark/placemark.kml'
        ..suppressInfoWindows = true
        ..map = map);
```

Thanks!

**Comment by a14n** [comment]
Your question is rather related to the usage of the [google maps API](https://developers.google.com/maps/documentation/javascript). I'd recommend [asking on StackOverflow](https://stackoverflow.com/questions/tagged/google-maps-api-3). Once you get a good answer don't hesitate to come back to me if you have some difficulties to translate it to Dart.
