### ISSUE TITLE
getPanorama throw a exception when consult not available location for streetview

### ISSUE THREAD

**Issue by lautarozanuttini** [a14n/dart-google-maps#116]
Hi a14n, a im using the package to consult locations but if its not available throw a exception in this functions, the solutions that will help its convert the value that return from StreetViewResponse to StreetViewResponse? 

```dart
extension StreetViewService$Ext on StreetViewService {
  Future<StreetViewResponse> getPanorama(
    Object? /*StreetViewLocationRequest?|StreetViewPanoRequest?*/ request, [
    void Function(StreetViewPanoramaData?, StreetViewStatus?)? callback,
  ]) =>
      promiseToFuture(callMethod(this, 'getPanorama', [
        request,
        callback == null
            ? null
            : allowInterop((p0, p1) => callback(p0, StreetViewStatus$cast(p1)))
      ]));
}
```

getPanorama(), on line 6126 on google_maps_core.js.g.dart. thanks

**Comment by a14n** [comment]
I don't understand the issue. [The example 08-services/streetview-service](https://github.com/a14n/dart-google-maps/tree/master/example/08-services/streetview-service) works without issue even on location without streetview (the check of the status allows you to catch those cases)?

**Comment by lautarozanuttini** [comment]
Hi Alexandre, im using flutter_street_view package where use this package to find location and show the view but flutter throw error in this functions everytime that location is not available, here attached images with the error.  Thanks you for the patience.

![196828970-41bf00ba-4275-49bd-a56f-a7409f0ece32](https://user-images.githubusercontent.com/79458253/197786493-fdf6cadc-1516-47f9-913d-a662adbf1b5c.png)
![197032348-a84ff17c-bc42-4291-830b-8271aaf367b9](https://user-images.githubusercontent.com/79458253/197786505-ffda0b3d-6c4e-4319-8c16-81f65c353bfd.png)

**Comment by a14n** [comment]
Do you use a specific version of google maps? What returns `google.maps.version` in the js console?

According to [the getPanorama doc](https://developers.google.com/maps/documentation/javascript/reference/street-view-service#StreetViewService.getPanorama) this method should return a promise (and not `null` as the logs suggest)

Could you share your `getPanorama()` call?

**Comment by lautarozanuttini** [comment]
im using  google_maps_flutter: ^2.1.12,  google_maps_flutter_web: ^0.4.0+2 and flutter_google_street_view: ^3.1.2, i will send you more info latter because im not in the office now.

**Comment by a14n** [comment]
Is this issue still relevant?

**Comment by lautarozanuttini** [comment]
Hi Alexandre, i had to close another things but yesteday i execute flutter clean, update all packeges and re-code the widget that have this issue and didnt show anymore, i think that was the solution, i will keep testing and if show up again then i re-open this issue, im sorry for the time and thank you for your patience.

**Comment by lautarozanuttini** [comment]
Hi Alexander, here is the error again and that is the call to the getPanorama function.

![image](https://user-images.githubusercontent.com/79458253/198720393-ec591fb7-4b18-42b8-bb9a-99eaf3707e9a.png)
![image](https://user-images.githubusercontent.com/79458253/198720550-2efd2dcd-3c08-47fa-9eda-7651682bc605.png)

**Comment by a14n** [comment]
Do you use a specific version of google maps? What returns `google.maps.version` in the js console of your browser?

Could you provide a simple project that reproduce the issue? I'm not able to see this issue on the [example 08-services/streetview-service](https://github.com/a14n/dart-google-maps/tree/master/example/08-services/streetview-service).
