### ISSUE TITLE
Multiple Dependency Issue

### ISSUE THREAD

**Issue by Snehal-Singh174** [a14n/dart-google-maps#118]
while adding googleMap inside a class that also has Icon supported by flutter widgets then getting conflict of imports issue

<img width="923" alt="Screenshot 2023-03-30 at 3 33 30 PM" src="https://user-images.githubusercontent.com/53808476/228802999-509675ea-6a1d-4fd4-af76-57846c4ccee3.png">

**Comment by a14n** [comment]
You can hide this class on the import directive:

```dart
import 'package:google_maps/google_maps.dart' hide Icon;
```

or import google_maps with a prefix:

```dart
import 'package:google_maps/google_maps.dart' as gmaps;
```
