### ISSUE TITLE
Using legacy MapLabel JS from flutter application

### ISSUE THREAD

**Issue by jozes** [a14n/dart-google-maps#121]
Hello!
Is it possible to use MapLabel https://github.com/googlearchive/js-map-label together with google_maps in dart/flutter? If yes, how this could be done? I have an old project where the MapLabel is used and we are planning now to move it from PHP / HTML / JS to Flutter web application and the MapLabel to display text over polygons is one of the crucial requirements.

Thanks in advance for yor help.

**Comment by jozes** [comment]
After a bit of researching the problem I found a good solution without this legacy MapLabel. So no need to answer that. But I came to another problem or better say question. Are there any plans to implement Google Maps markers library and add that to this package, so we can use the advanced options for marker configuration.

**Comment by a14n** [comment]
Glad you found a solution.

> Are there any plans to implement Google Maps markers library and add that to this package

No. The initial intent was to provide a simple dart wrapper for google maps js API.
