### ISSUE TITLE
Support to wasm

### ISSUE THREAD

**Issue by JgomesAT** [a14n/dart-google-maps#130]
Steps to reproduce
Build to WASM version

Expected results
build succesfully

Actual results
../../../../.pub-cache/hosted/pub.dev/google_maps-7.1.0/lib/src/generated/google_maps_core.js.g.dart:26:8: Error: Dart library 'dart:web_gl' is not available on
this platform.
import 'dart:web_gl' show RenderingContext;
^
Context: The unavailable library 'dart:web_gl' is imported through these packages:

web_plugin_registrant.dart => package:google_maps_flutter_web => package:google_maps => dart:web_gl
../../../../.pub-cache/hosted/pub.dev/google_maps-7.1.0/lib/src/generated/google_maps_core.js.g.dart:977:12: Error: Type 'RenderingContext' not found.
external RenderingContext? get gl;
^^^^^^^^^^^^^^^^
../../../../.pub-cache/hosted/pub.dev/google_maps-7.1.0/lib/src/generated/google_maps_core.js.g.dart:979:19: Error: Type 'RenderingContext' not found.
external set gl(RenderingContext? value);
^^^^^^^^^^^^^^^^
../../../../.pub-cache/hosted/pub.dev/google_maps-7.1.0/lib/src/generated/google_maps_core.js.g.dart:991:12: Error: Type 'RenderingContext' not found.
external RenderingContext? get gl;
^^^^^^^^^^^^^^^^
../../../../.pub-cache/hosted/pub.dev/google_maps-7.1.0/lib/src/generated/google_maps_core.js.g.dart:993:19: Error: Type 'RenderingContext' not found.
external set gl(RenderingContext? value);

**Comment by OlegShNayax** [comment]
Any updates?

**Comment by a14n** [comment]
I'm working on a new version based on the new js interop that should support wasm compilation.
Unfortunatelly I do it on my spare time and that migration is a huge task.

**Comment by kevmoo** [comment]
@a14n – what's your schedule to publish a stable version of this? It'd likely be good to wait for us to validate https://github.com/flutter/packages/pull/7077 – but we likely don't want to land/publish that until you're released stable.

**Comment by Rexios80** [comment]
@kevmoo I'd like to resolve all issues with WASM integration tests in `google_maps_flutter_web` before we push @a14n to push this to stable, but getting WASM integration tests working is blocked by a lot of things on the Flutter side.

**Comment by a14n** [comment]
I'm not in a hurry and I planned to wait that flutter_google_maps works correctly before publishing a stable version.

**Comment by kevmoo** [comment]
@a14n – we're ready for a stable release of `8.0.0` if you're game. 

Thank you SO MUCH for your work here! 🙏

**Comment by a14n** [comment]
8.0.0 published

**Comment by kevmoo** [comment]
> 8.0.0 published

thank you!!! 🙏

**Comment by JgomesAT** [comment]
with this new version is till required the google_maps _flutter_web?

**Comment by JgomesAT** [comment]
But this library google_maps _flutter_web is not update yet

**Comment by Rexios80** [comment]
It's almost done

https://github.com/flutter/packages/pull/7077
