### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'Fg') 

### ISSUE THREAD

**Issue by 0hsoyeop** [a14n/dart-google-maps#134]
I am using the Google Maps in my Flutter web application. However, I have recently been encountering the following error in debug console, and the Google map is intermittently not displaying:

```
TypeError: Cannot read properties of undefined (reading 'XXX')
https://maps.googleapis.com/maps/api/js?key=MY_API_KEY
```

The error below is displayed when using the Chrome browser.
``
Exception while loading service worker: DOMException: Failed to register a ServiceWorker for scope ('http://localhost:3000/') with script ('http://localhost:3000/flutter_service_worker.js?v=null'): The Service Worker system has shutdown.
``

Sometimes the map displays normally, but other times the above error occurs and the map does not show up.
What is the problem? I have not made any changes to the Google map settings on my own.
I would appreciate any advice on how to resolve this issue.
The version I am using is google_maps: ^7.1.0.

```

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.19.6, on Microsoft Windows [Version 10.0.19045.4651], locale ko-KR)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.6.5)
[√] Android Studio (version 2022.2)
[√] IntelliJ IDEA Ultimate Edition (version 2023.3)
[√] VS Code (version 1.91.1)
[√] Connected device (3 available)
[√] Network resources

• No issues found!
```

**Comment by a14n** [comment]
Hard to tell without additional context. 

FWIW I just published a pending 8.0.0-dev.2 that could fix this issue as it looks like #133 . Could you test against this version?

If you still face the issue could you provide a reproduction case? It would be very useful.
