### ISSUE TITLE
OverlayView with tilt

### ISSUE THREAD

**Issue by fne00** [a14n/dart-google-maps#137]
I overlay tiles from a KMZ file with OverlayView.

This works well, except when the underlying map is tilted or rotated (using the default controls on the map when zoomed in).

My draw function is:
```
 void _draw() {

    final overlayProjection = overlayView.projection!;

    final sw = overlayProjection.fromLatLngToDivPixel(_bounds.southWest)!;
    final ne = overlayProjection.fromLatLngToDivPixel(_bounds.northEast)!;

    final div = _div!;
    div.style
      ..left = '${sw.x}px'
      ..top = '${ne.y}px'
      ..width = '${ne.x! - sw.x!}px'
      ..height = '${sw.y! - ne.y!}px'
      ..opacity = '${opacity}'
      ..transform = 'rotate(${-(double.tryParse(_rotation) ?? 0.0)}deg)';
  }
  ```

It appears that the `overlayProjection.fromLatLngToDivPixel` does not handle tilting/rotation?
Or am I missing something?

Without tilt:
<img width="427" alt="Screenshot 2024-08-12 at 7 35 16 AM" src="https://github.com/user-attachments/assets/cb4bdd6b-db48-4513-a75d-cd3a66827f1e">

With Tilt:
<img width="431" alt="Screenshot 2024-08-12 at 7 32 00 AM" src="https://github.com/user-attachments/assets/a502ced5-c06c-4574-bbfd-6ca71648c1c5">

**Comment by a14n** [comment]
Interesting topic! This problem is not related to google_maps package, you should have the same problem with a JS implementation. I don't have free time to search for a solution but I guess other people on the JS world had faced the same issue. Try to google/stackoverflow your problem in the JS world.

**Comment by fne00** [comment]
Thanks - Will look in the JS world as suggested.
