### ISSUE TITLE
MapType objects not accepted by MapTypeRegistry

### ISSUE THREAD

**Issue by stevenroose** [a14n/dart-google-maps#28]
I'm trying to do something similar to [this ImageMapType example](https://developers.google.com/maps/documentation/javascript/maptypes#ImageMapTypes).

However, when I try to add my `ImageMapType` object to the `MapTypeRegistry`, it raises this exception: `Exception: Error: Expected value implementing google.maps.MapType`.

I'm 100% positive the object passed is a `MapType` object, so the error must originate from the wrapped JS.

**Comment by a14n** [comment]
Are you looking for [this example](https://github.com/a14n/dart-google-maps/tree/master/example/06-maptypes/maptype-image) ?

**Comment by stevenroose** [comment]
This post helped me fix this: https://groups.google.com/forum/#!topic/google-maps-js-api-v3/zpe8OlyqEII

It seems that if not all required properties are set, you get that (somewhat misleading) error message.

But it's fixed now, I'll close the issue.
