### ISSUE TITLE
fail to create PlacesService object - /example/10-places/place-search failing

### ISSUE THREAD

**Issue by alextekartik** [a14n/dart-google-maps#32]
I was getting "Uncaught TypeError: undefined is not a function" in my after creating a PlacesService object. After looking carefully on my side, I noticed the same happen in some code examples.
If you take a look at /example/10-places/place-search/page.dart, you'll see that the example is no longer working and the error is thrown (final service = new PlacesService(map); is causing the error asynchronously)

**Comment by alextekartik** [comment]
Reverting to google map 2.0.7 works fine in my code (minus some minor API change in textSearch)

**Comment by a14n** [comment]
Thanks for the report.

That seems to be a problem with objects having a constructor accepting union types. `PlacesService(dynamic /*HTMLDivElement|GMap*/ attrContainer)` here.

I will try to publish a fix quickly.

**Comment by a14n** [comment]
Fixed by e5cbfc5dde6ffdcc03e95757c034dead40f7f353.

Published in version _3.0.2_
