### ISSUE TITLE
Can't set AutocompletionRequest.componentRestrictions.country

### ISSUE THREAD

**Issue by domesticmouse** [a14n/dart-google-maps#35]
Hey Alexandre,

I'm trying to create an `AutocompletionRequest` with a country restriction. My code currently looks like this:

      var request = new AutocompletionRequest()
        ..bounds = _map.bounds
        ..input = query
        ..types = ['geocode']
        ..componentRestrictions.country = 'au';

But I'm seeing the following in my console:

    NullError: method not found: 'set$country' on null

Which is totally not what I'm looking for. Halp?

**Comment by a14n** [comment]
You should try :

```dart
var request = new AutocompletionRequest()
  ..bounds = _map.bounds
  ..input = query
  ..types = ['geocode']
  ..componentRestrictions = (new ComponentRestrictions()..country = 'au');
```

When you create a `AutocompletionRequest` there's no `ComponentRestrictions` automatically set.

**Comment by domesticmouse** [comment]
Of course! Works nicely, thanks!
