### ISSUE TITLE
PlacePhoto does not have a getUrl method.

### ISSUE THREAD

**Issue by Andruj** [a14n/dart-google-maps#38]
Hi - I am attempting to use the Google Maps API in Dart to get images based on geolocated coordinates. I was looking into the JsInterop files, which has a getUrl method - but that method does not exist on the Dart side. Is there another way to get the Url of the PlacePhoto?

**Comment by Andruj** [comment]
Yes, it does not seem to register as a method. After I have done a place details request, I have an array of PlacePhoto. When looking at their properties they don't have a method called getUrl, and trying to call it (assuming the analyzer wasn't reading the generated class structures properly) causes a exception as it is not a property.

**Comment by Andruj** [comment]
Can you recreate this issue?

**Comment by a14n** [comment]
No, it works for me.

To test I added the following code to [the place-details example](https://github.com/a14n/dart-google-maps/tree/master/example/10-places/place-details) at the [line 19 of page.dart](https://github.com/a14n/dart-google-maps/blob/master/example/10-places/place-details/page.dart#L19)

```dart
      print(place.photos
          .map((p) => p.getUrl(new PhotoOptions()..maxWidth = 1000))
          .join('\n'));
```

Dartium outputs into the console :

```
https://lh3.googleusercontent.com/-lZvBaeRLDII/VQKE2mBxDjI/AAAAAAAAQ_Y/PnORzvS1VykhkpKJWYxQQdVoS3NPgMHyA/w1000-k/
https://lh4.googleusercontent.com/-ic5yp2EfTqE/WBEln0fmFvI/AAAAAAAAQ-o/mMqYawGk0aIeNqFcNm57A-7NkZxuEcOyQCLIB/w1000-k/
https://lh3.googleusercontent.com/-1Fccckx6qzw/V0bhVgTB9BI/AAAAAAAABFU/wB0HwHeXewI7f-gj8Qnnbscao-jpGbSXQCLIB/w1000-k/
https://lh5.googleusercontent.com/-CJ1ZrhNl_P0/Vyb4gZO5hpI/AAAAAAAAar0/Mk0-LeVa4xQIHoYW9Cf4jZGLTHJBR7RzwCLIB/w1000-k/
https://lh6.googleusercontent.com/-IBKhgDY-GU0/Vx4irGqpF7I/AAAAAAAAPpE/ryUEVyfvWgY4oTnDSQr6ZhNwrP8NJypXQCLIB/w1000-k/
https://lh6.googleusercontent.com/-OgLBnO2n0NY/V4xq1lMja7I/AAAAAAAAS3s/0R6sv9POlzAoamPgXgazjHwzBKEDAiYEgCLIB/w1000-k/
https://lh5.googleusercontent.com/-4w1Cv-aBpw0/V995qVDNr4I/AAAAAAABjxY/nBUaHE20R_M9xWpWafU7bP9FZFwiaxEvACLIB/w1000-k/
https://lh4.googleusercontent.com/-35VJXcxLBWA/WAhgVgdh0QI/AAAAAAAAKdw/U-3vH2fvoeMJ0ihWLVJMwoZ_iRQCdh1pACLIB/w1000-k/
https://lh6.googleusercontent.com/-WMVVUCRgKfo/VyPk-kvnZDI/AAAAAAACwZU/zJn_p2_y9HUVly8ftRZqjw-F2VPuTcSygCLIB/w1000-k/
https://lh5.googleusercontent.com/-gxIsZgsWZXY/VxrdEQHoDbI/AAAAAAABh_w/3vyb__reDzEqujbMbs-Q1A_FHR46AQeKwCLIB/w1000-k/
```

**Comment by Andruj** [comment]
I will try this and get back. Thanks!

**Comment by Andruj** [comment]
So, I tried it, but it still does not recognize the getUrl function. I attached my pubspec.yaml and a screenshot of the analyzer.

**Comment by Andruj** [comment]
Okay, I figured it out. The issue is that in order to use the version 3.1.0 of the google_maps package, you need a greater than 0.2.0 of the package js_wrapping. Currently, there is no such version, so pub degrades google_maps to 2.0.7. I will try installing a more current version.

**Comment by Andruj** [comment]
Should it be js_wrapping: ^0.2.0? or should it be '>=0.2.0'....

https://pub.dartlang.org/packages/js_wrapping

right now I do not see a version that would ever allow you to use 3.1.0.

**Comment by a14n** [comment]
See the [pubspec.yaml of version 3.1.0](https://github.com/a14n/dart-google-maps/blob/v3.1.0/pubspec.yaml). You can take a look at https://github.com/a14n/dart-google-maps/issues/37#issuecomment-251652412 - that's a pubspec.yaml that works for me with angular2 and google_maps (particularly see the dependency_overrides section)

**Comment by a14n** [comment]
no dependency_overrides should be needed starting from `google_maps-3.2.0`
