### ISSUE TITLE
Move to pkg/js – away from js_wrapping

### ISSUE THREAD

**Issue by kevmoo** [a14n/dart-google-maps#39]
Would be super nice 😄

**Comment by a14n** [comment]
It's something I'm looking at but:

1. I'd like to keep the same public API ( that means wrapping almost every objects - btw once dart-lang/sdk#24779 fix wrapping could be removed )
2. It's not that simple regarding the size of the package

**Comment by Andruj** [comment]
Right now, this is breaking using google_maps with angular2. Pub will resolve to angular2: 2.0.0-alpha 6 because of the js_wrapping dependency in Google Maps ^3.0.0

**Comment by a14n** [comment]
@Andruj as I said in #38 using `dependency_overrides` solves your issue...

**Comment by kevmoo** [comment]
Can we update `js_wrapping` ?

**Comment by a14n** [comment]
@kevmoo I'm working on it :)

**Comment by erikist** [comment]
Pinging to see what the status on this is: I am having an issue using `google_maps` and the `pwa` package.

**Comment by jmesserly** [comment]
Yeah definitely, rename support is critical. Thanks for letting me know about that bug!

**Comment by jmesserly** [comment]
Oh also, yeah google_maps would be a great test case!

js_wrapping is a great source of inspiration too, by the way. I hope the new compiler support will have quite a similar feel, from a usability perspective. (And the compilers should be able to avoid wrappers, generally speaking.)

**Comment by a14n** [comment]
Version 4.0.0 now uses `package:js` instead of `dart:js`.
