### ISSUE TITLE
Futures instead of Callback functions

### ISSUE THREAD

**Issue by Blackbam1337** [a14n/dart-google-maps#43]
In my opinion this library would be way more dart-alike if you would use Futures instead of callback functions.

Example of what I have to do:

```dart
  Future<LatLng> getLatLngFromString(String address) {
    var completer = new Completer<LatLng>();
    _geocoder.geocode(
        new GeocoderRequest()
          ..address = address,
        (results, status) => status == GeocoderStatus.OK
            ? completer.complete(results[0].geometry.location)
            : completer.completeError(
                'Geocode was not successful for the following reason: ' +
                    status.toString()));
    return completer.future;
  }
```

It would be better if Futures would be returned directly.

**Comment by a14n** [comment]
It's something I wanted to do at the start of the lib but: 

1. it was not obvious if/what status should be handle as error (re. Future).  For instance see [GeocoderStatus](https://github.com/a14n/dart-google-maps/blob/e62678b6705f7c59dca4f9a59d89cc3894fa2df2/lib/src/core/services/geocoder_status.dart#L20-L26).
2. it's more simple for someone looking at the [google maps api for JS](https://developers.google.com/maps/documentation/javascript/3.exp/reference) to produce a code that works.

This is something I'll change perhaps when I'll refactor the lib for Dart 2
