### ISSUE TITLE
Split and document an importable that doesn't use 'dart:html'

### ISSUE THREAD

**Issue by xster** [a14n/dart-google-maps#49]
Could part of this library like geocoding etc be split from the map embedding mechanism and let the html-less library be used in Flutter?

**Comment by a14n** [comment]
For now this package is only a wrapper around the [Maps JavaScript API](https://google-developers.appspot.com/maps/documentation/javascript) and does need a js runtime to work.

I'll take a look to provide a library to consume [Maps Webservices API](https://google-developers.appspot.com/maps/web-services/)

**Comment by xster** [comment]
Ah makes sense. Look forward to it :)

**Comment by a14n** [comment]
Actually there already [a package using MapsWebservices API](https://pub.dartlang.org/packages/google_maps_webservice) available on pub.
