### ISSUE TITLE
Key code on mouse click event

### ISSUE THREAD

**Issue by vnerozin** [a14n/dart-google-maps#52]
MouseEvent class do not contain key codes.
Is it possible to get key code on mouse click event?
 
```
   final mapOptions = new gmap.MapOptions()
      ..zoom = 8
      ..disableDoubleClickZoom = true
      ..center = new gmap.LatLng(41.850033, -87.6500523);

    map = new gmap.GMap(mapRoot, mapOptions);

    map.onClick.listen((gmap.MouseEvent me) {
      // TODO How to get key code there?
      //if (me.ctrlKey || me.metaKey)
      addMarker(me.latLng, ctrlClick);
    });
```

**Comment by a14n** [comment]
The underlying js object ([MouseEvent](https://developers.google.com/maps/documentation/javascript/reference#MouseEvent)) doesn't have `ctrlKey` or `metaKey`. So the dart API cannot expose them.

I guess you have to listen to keydow/keyup events on the map div to be able to do what you want.
