### ISSUE TITLE
MultiPolygons not working for more than 2 polygons.

### ISSUE THREAD

**Issue by EoinAviation** [a14n/dart-google-maps#58]
When creating a MultiPolygon (Where one creates a hole inside of the other, like a doughnut), adding a 3rd polygon does not create a hole as expected.

The mouse cursor will act as though there is a hole, but the main polygon is still being displayed:
![image](https://user-images.githubusercontent.com/25342760/41497354-3a5362cc-7197-11e8-8037-4491e35dd3d0.png)

Is this a Google Maps API limitation?

**Comment by a14n** [comment]
I don't really know. I cannot find any reference of such a limitation. So it may be a limit in Maps JS api (you can test a simple example directly in JS code) or an issue in what you display on the map (perhaps a polygon under an other) or a bug in the Dart wrapper (but I don't see what would lead to this behaviour).

**Comment by EoinAviation** [comment]
Just tested in plain JS. Seems to be a Google Maps API problem. I've submitted a bug report directly to them. Hopefully they solve this quickly.
