### ISSUE TITLE
Google Maps Point has no such method "y" when using getTileUrl

### ISSUE THREAD

**Issue by EDToaster** [a14n/dart-google-maps#61]
In my webapp, I am using a custom Tile Server to get the map tiles.

However when using ImageMapTypeOptions and setting getTIleUrl by using the following code:

```
ImageMapTypeOptions()
      ..getTileUrl = (g.Point coord, double zoom) {
        return "https://..url../$zoom/${coord.x}/${coord.y}?access_token=$API_KEY";
      }
```

I get the error that coord has no method "y".

When using the code `print(coord.y)`, i always get "null" as output.

Cheers!

**Comment by a14n** [comment]
`getTileUrl` is a little special to work with and you cannot directly set this function (I hadn't time to improve that).

To make it work you can have a look at:

https://github.com/a14n/dart-google-maps/blob/e8199659920c59b1d573583a1dcd8f10e5ae9f42/example/01-basics/map-projection-simple/page.dart#L108-L132

**Comment by EDToaster** [comment]
Thanks, will check out.

**Comment by a14n** [comment]
In version 3.4.0 you can now directly use `getTileUrl` setter

https://github.com/a14n/dart-google-maps/blob/f4d7e0f8a149d0773df02aff5db2e05c0055d37b/example/01-basics/map-projection-simple/page.dart#L107-L122
