### ISSUE TITLE
In release mode in Flutter for web, we cannot call an event listener on a map marker

### ISSUE THREAD

**Issue by corymalcolmtaylor** [a14n/dart-google-maps#72]
Hi,
Is this project still supported?
I was trying to use it to target "Flutter for Web"  and ran into a problem that I thought was due to something external to this package and related to the flutter build process but it got closed over there so I'll link it here just in case you want to have a  look:
[https://github.com/flutter/flutter/issues/54026](https://github.com/flutter/flutter/issues/54026)

**Comment by a14n** [comment]
>Is this project still supported?

Yes :)

> flutter/flutter#54026

It looks like an issue with Flutter Web or your code.

Thanks for pointing the issue.

**Comment by corymalcolmtaylor** [comment]
Interesting,  I'd like to test a release build but without the tree-shaking, is there a way to turn off tree-shaking when building the app?

**Comment by alanstyong71** [comment]
You can see my comments to the above issue.

**Comment by a14n** [comment]
Closing as [google_maps_flutter](https://pub.dev/packages/google_maps_flutter) is out.
