### ISSUE TITLE
Flutter widget communicating with Javascript elements in Google Maps

### ISSUE THREAD

**Issue by alanstyong71** [a14n/dart-google-maps#74]
Hi,

Firstly, thanks for developing this library. Definitely a life saver since the Flutter team hasn't built Web support for the official Google Maps plugin yet. 

I am developing an application that is iOS, Android and Web. The web version uses this plugin. 

<img width="814" alt="Screen Shot 2020-04-14 at 12 38 27 PM" src="https://user-images.githubusercontent.com/57510861/79186771-21086000-7e4d-11ea-8a80-42f49be027a9.png">

I have an App Bar that shows the Google Map of a location and related locations, and a Sliver List (SliverFixedExtentList) that scrolls up to show different locations. 

Question: 

How do I communicate with the Google Map above from the ListTiles below? I have an OnTap() on each ListTile that calls the InfoWindow.open function. This works well in the official Google Map plugin, but breaks here.

I have tried the following: 

When GMap is built, the Markers are stored in a list of Markers to retrieve later when the ListView is being built. This fails and the map will not render. Any setState will result in the map not being rendered.

So now I'm thinking - since the map is Javascript and rendered as a HTML object, there is no way for Flutter/Dart to get to that object, unless those objects are exposed. It is not a Flutter/Dart widget.

I've been investigating on setting a DIV id on the InfoWindows, and calling the Click event, since I bound it when I created the map, but I got lost somehow. I cannot store the InfoWindow object as a flutter widget and call it in Flutter.

Could someone point me in the right direction?

Thanks very much,
Alan

**Comment by a14n** [comment]
Do you have a simple public projet I could use to figure out what is going on?

**Comment by GeoGlass** [comment]
> When GMap is built, the Markers are stored in a list of Markers to retrieve later when the ListView is being built. This fails and the map will not render. Any setState will result in the map not being rendered.

I had the same issue when I try to rebuild and change state. A workaround is to create a different htmlId on every rebuild like: 

`final String htmlId = "my-maps-" + DateTime.now().millisecondsSinceEpoch.toString();`

It worked for me.

I hope it helps.

**Comment by alanstyong71** [comment]
@GeoGlass Thanks for the hint, give me a few days to try it out and I'll report back.

**Comment by a14n** [comment]
Closing as [google_maps_flutter](https://pub.dev/packages/google_maps_flutter) is out.
