### ISSUE TITLE
Add support for GoogleMap.setPadding() method.

### ISSUE THREAD

**Issue by dazyday** [a14n/dart-google-maps#76]
First of all I would like to say thank you very much for this package, it works great for flutter web. 

One thing that would actually really help build fullscreen UIs would be the GoogleMap.setPadding() method -- this adds padding of all the Google Map UI elements (logo, controls, etc) while still maintaining a fullscreen map.

Unfortunately I am still a total script kiddie so I haven't been able to figure it out quite yet.

Thank you for all you do!

**Comment by a14n** [comment]
Thanks for the interest.

This package is a wrapper on top of the javascript api and I don't plan to add additional features not corresponding to something in the javascript api.

You should so handle padding directly in your app. Sorry.

**Comment by dazyday** [comment]
https://github.com/flutter/flutter/issues/32149 This is the method I was referencing, sorry that I didn't include it originally. Thank you for your time.
