### ISSUE TITLE
Google Map absorbing clicks to elements higher in a stack 

### ISSUE THREAD

**Issue by randomdude583** [a14n/dart-google-maps#82]
If the map is placed in a Stack, and other elements are placed above the map, the map will consume all touch events. Map can be dragged, and onTap fired through the above elements. This issue also seems to be an issue in all libraries I have found that depend on this library.

I also created an issue in the flutter_google_maps repository [here](https://github.com/marchdev-tk/flutter_google_maps/issues/23)

**Comment by a14n** [comment]
It doesn't look related to _google_maps_ package but rather related to its flutter integration.

**Comment by joaquini** [comment]
Can confirm this issue is happening. Even wrapping the GoogleMap into a IgnorePointer it consumes also the touch events.

**Comment by tomrozb** [comment]
@a14n looks like all the Flutter packages that provide Google Maps are based on google_maps package and have exactly the same issue. Can it be solved somehow in this package? Any thoughts?

**Comment by ditman** [comment]
This is a known Flutter Web issue, see this (there's probably more examples):

https://github.com/flutter/flutter/issues/54027

**Comment by a14n** [comment]
Closing as flutter/flutter#54027 is now closed.
