### ISSUE TITLE
A release with  "migrate from dart:js to package:js" please

### ISSUE THREAD

**Issue by gustav3d** [a14n/dart-google-maps#84]
Hello,

I would like to test the "migrate from dart:js to package:js" commit with the https://pub.dev/packages/flutter_google_maps project .

But it seems not possible to upgrade a sub dependency to a git source.

Can you make a new release ?:) 

best regards
  Gustav

**Comment by a14n** [comment]
It's still a _work in progress_ because I'd like to investigate/address some issues.

Unfortunatelly I had to put this work aside for some times. Hope to find time to work on it in the next weeks/month.

**Comment by gustav3d** [comment]
Thanks for the quick response.
Alright, I understand.

Are there any currently known issues with it ?.

**Comment by a14n** [comment]
IIRC there are 2 main issues:

* every callback needs to be wrap with `allowInterop` and I'd like to automatically do that (but it's not possible for contructor and static methods)
* issues with enums and their underlying types. I'd like to avoid using `dynamic/Object` but it's the only workaround I found for now.

**Comment by gustav3d** [comment]
Thanks for the explanation of the situation.

I would like to delve into this, but I'm overwhelmed with work by being
alone in my current project :(

**Comment by carloshwa** [comment]
Would it be possible to rebuild the `v3` branch against the latest Google Maps JS library? It looks like it's currently built against an older version, and there are some missing APIs (specifically looking at the Autocomplete library). Or are there steps so that we can re-build it ourselves locally?

**Comment by a14n** [comment]
Unfortunately the v3 branch was build with something that is completely broken today. To make some changes I have to make manual changes (and that's not always simple)

**Comment by a14n** [comment]
Version 4.0.0 is published
