### ISSUE TITLE
map.projection.fromPointToLatLng not correctly bound to projection object?

### ISSUE THREAD

**Issue by ditman** [a14n/dart-google-maps#87]
I'm trying to use the `fromPointToLatLng` method of **the default `projection`** of the map, but I'm getting an error:

```
TypeError: Cannot read property 'y' of undefined.
```

when I call it like this:

```dart
// original JS by: Byron Singh (https://stackoverflow.com/a/30541162)
gmaps.LatLng _pixelToLatLng(gmaps.GMap map, int x, int y) {
  final ne = map.bounds.northEast;
  final sw = map.bounds.southWest;
  final projection = map.projection;

  final topRight = projection.fromLatLngToPoint(ne);   //
  final bottomLeft = projection.fromLatLngToPoint(sw); // <- This two calls work

  final scale = 1 << map.zoom; // 2 ^ zoom

  final point = gmaps.Point((x / scale) + bottomLeft.x, (y / scale) + topRight.y);

  return projection.fromPointToLatLng(point); // <- This blows up!
}
```

Digging in the JS code a little bit, it seems that when I call the method, `this.H` is undefined:

<img width="1123" alt="Screen Shot 2020-08-15 at 9 21 35 PM" src="https://user-images.githubusercontent.com/1255594/90326598-0b13c480-df3f-11ea-8921-dc3da5183854.png">

And `this` is the Window object (from other successful calls of that method, `this` seems to be an instance of a `Projection` object).

That `this` is Window made me suspect that `fromPointToLatLng` is not correctly bound to the `projection` object (but my knowledge of this lib is not enough to locate the exact error in Dart :S)

I'm using v**3.4.4** of google_maps, according to my pubspec.lock:

```
  google_maps:
    dependency: transitive
    description:
      name: google_maps
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.4.4"
```

**Comment by a14n** [comment]
Sorry for the delay.

It looks really close to #81 . I'll try to fix that.

**Comment by ditman** [comment]
Ouch! Sorry I didn't find #81, I would have reopened it (x_x)

**Comment by a14n** [comment]
no, no, it is another issue but with the same behaviour.

The 3.4.5 version should fix this issue.
