### ISSUE TITLE
Plus Code is not supported by the Dart wrapper

### ISSUE THREAD

**Issue by YuzuruT** [a14n/dart-google-maps#90]
The GeocoderResult class does not seem to unpack any of the [Plus Code data](https://maps.google.com/pluscodes/#:~:text=What%20are%20Plus%20Codes%3F,displayed%20as%20numbers%20and%20letters.) supplied from the API calls to GeoCodeService.

**Comment by a14n** [comment]
Is it really related to the Dart wrapper? After a quick look at the [Google Maps JavaScript API V3 Reference](https://developers.google.com/maps/documentation/javascript/reference) I haven't seen any reference to Plus Code. Do you have an example with the JS api that works with a PlusCode?

**Comment by YuzuruT** [comment]
Thank you for your prompt response.

I see. It does seem a bit odd.
Although I do see documentation about PlacePlusCode
<https://developers.google.com/maps/documentation/javascript/reference/places-service#PlacePlusCode>,
it seems the documentation for GeocoderResponse
<https://developers.google.com/maps/documentation/javascript/reference/geocoder#GeocoderResponse>
and
GeocoderResult
<https://developers.google.com/maps/documentation/javascript/reference/geocoder#GeocoderResult>
both
do not include the PlacePlusCode field. Yet, in the JSFiddle example
<https://developers.google.com/maps/documentation/javascript/geocoding#> of
ReverseGeocoding
<https://developers.google.com/maps/documentation/javascript/geocoding#ReverseGeocoding>,
I clearly see PlacePlusCode
<https://developers.google.com/maps/documentation/javascript/reference/places-service#PlacePlusCode>
in both GeocoderResponse
<https://developers.google.com/maps/documentation/javascript/reference/geocoder#GeocoderResponse>
and
GeocoderResult
<https://developers.google.com/maps/documentation/javascript/reference/geocoder#GeocoderResult>.
Attached image shows PlacePlusCode inside GeocoderResult.

I arrived here by Google searching "how to get Plus Code from LatLng" and
ReverseGeocoding was the recommendation, only to find that these fields
didn't pipe through to the Dart impl response.

While "plus_code" is included in the *type* field of
GeocoderAddressComponent
<https://developers.google.com/maps/documentation/javascript/reference/geocoder#GeocoderAddressComponent>,
both *long_name* and *short_name *are not the full 10 digit Plus Code which
is not very useful if one wants the exact location via a single Plus Code
string.

I am new to this process.
I assume my next step should be to request Maps API documentation to add
PlacePlusCode as an official field of GeocoderResponse/Result?


2020年12月3日(木) 1:36 Alexandre Ardhuin <notifications@github.com>:

**Comment by a14n** [comment]
As you point out `plus_code` can be used in [GeocoderResult.types](https://developers.google.com/maps/documentation/javascript/reference/geocoder#GeocoderResult.types) or [GeocoderAddressComponent.types](https://developers.google.com/maps/documentation/javascript/reference/geocoder#GeocoderAddressComponent.types) to indicate that `long_name` and/or `short_name` is a [PlusCode](https://maps.google.com/pluscodes/).

I actually never saw a `plus_code` as result so it's not easy to answer your question.

I'm closing this issue because nothing need to be done on the code.
