### ISSUE TITLE
Flutter Web - marker animations only work when using SKIA

### ISSUE THREAD

**Issue by datayeah** [a14n/dart-google-maps#91]
When i add animation to my custom map markers, it works perfectly when using "--dart-define=FLUTTER_WEB_USE_SKIA=true" as build parameter.
As soon as i build the web app without SKIA, the map still works but animations are not shown. 

This is the code i use to animate the markers:

```
Marker marker = Marker(MarkerOptions()
          ..position =LatLng(
              num.parse(mapData[i]['lat']),
              num.parse(mapData[i]['lon']))
          ..icon = (Icon()
            ..url = "assets/static/pin_custom".png"
            ..map = map
            ..size = Size(99.0, 138.0)
            ..anchor = Point(24.0, 62.0)
            ..scaledSize = Size(48.0, 67.0))
          ..animation = Animation.DROP);

```
Any idea why it only works with SKIA?
I am using Flutter version 1.24.0-10.1.pre

**Comment by datayeah** [comment]
I found out that adding "--dart-define=FLUTTER_WEB_USE_SKIA=true" to the build command makes animations work. When this parameter is not included, animations don't work. I don't know if this is related to flutter itself or to this library then.

**Comment by a14n** [comment]
Yes this seems related to Flutter.
