### ISSUE TITLE
Support for styling via GCloud Console - new feature

### ISSUE THREAD

**Issue by funder7** [a14n/dart-google-maps#92]
Hello,

I've just discovered a new feature on GMaps documentation. 

Basically it allows to create a style from your GCP Console, and load it by defining a `mapId`in the map options.

It's quite nice because:
- Allows to define a style usable by many maps at the same time;
- Updating the style updates all the linked maps at once;
- It's possible to create variants for each Platform (Android, iOS, Javascript, static); 
- Javascript maps can be configured to use Vector or Raster;

Looks quite interesting to me, and probably easy to implement.

The feature is in beta at the moment, I've tried to create a new style and the editor looks identical to other version (the one which exports the style in JSON).

**Cloud based map customization - reference**
- [Android](https://developers.google.com/maps/documentation/android-sdk/cloud-based-map-styling)
- [iOS](https://developers.google.com/maps/documentation/ios-sdk/cloud-based-map-styling)
- [Javascript](https://developers.google.com/maps/documentation/javascript/examples/map-id-style)

I've forked the flutter_google_maps plugin from flutter/plugins and implemented the code to set this mapId (named as cloudMapId, to avoid confusion).

The problem is that I'm using Dart & Flutter since no more than 3 weeks, I would appreciate if somebody would help me in:
- understanding if this update is doable, or if there are any blockers;
- review the commits before of sending the PR; 

Thanks in advance... Flutter is Great!

**Comment by a14n** [comment]
This request seems to have a way to use this mapId on the flutter plugin so you should move this issue in the flutter repository.

I'll be happy to provide assistance on the JS implementation if the flutter maintainer of the Flutter google maps plugin accept this new feature.

**Comment by funder7** [comment]
You're right, I will forward the request on their repository then!
