### ISSUE TITLE
When release 4.0.0 is expected?

### ISSUE THREAD

**Issue by alexd1971** [a14n/dart-google-maps#93]
I'm waiting for property `className` of `MarkerLabel` which is implemented in 4.0.0

**Comment by a14n** [comment]
I'm still experimenting to find the best way to migrate from `dart:js` to `package:js`. As I do that on my free time the release of 4.0.0 can be in some days or in some weeks. Sorry.

**Comment by a14n** [comment]
version 4.0.0 is published
